version: 2
references:

  cache_key: &cache_key
    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key

  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle
        - ~/.m2

  workspace: &workspace
    ~/workspace

  chmod_permissions: &chmod_permissions
    run:
      name: Chmod permissions
      command: sudo chmod +x ./gradlew

  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-29
    environment:
      TERM: dumb
      JAVA_OPTIONS: "-Xmx3200m -XX:+UnlockExperimentalVMOptions -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx3200m" -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false -Dorg.gradle.caching=false'

jobs:
  dependencies:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - *chmod_permissions
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - *save_cache

  detekt:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - *chmod_permissions
      - run:
          name: Run Detekt
          command: ./gradlew detekt
      - store_artifacts:
          path: app/build/reports/
          destination: /reports/

  test_unit:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - *chmod_permissions
      - run:
          name: Run unit tests
          command: ./gradlew test -no-daemon -Pkotlin.incremental=false --max-workers=2
      - store_artifacts:
          path: app/build/reports/
          destination: /reports/
      - store_test_results:
          path: app/build/test-results/
          destination: /test-results/

  linter:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - *chmod_permissions
      - run:
          name: Run linter
          command: ./gradlew lint
      - store_artifacts:
          path: app/build/reports/
          destination: /reports/

workflows:
  version: 2
  workflow:
    jobs:
      - dependencies:
          filters:
            tags:
              only: /^.*/
      - detekt:
          requires:
            - dependencies
          filters:
            tags:
              only: /^.*/
      - test_unit:
          requires:
            - dependencies
          filters:
            tags:
              only: /^.*/
      - linter:
          requires:
            - detekt
            - test_unit
          filters:
            tags:
              only: /^.*/
